# generated by fastapi-codegen:
#   filename:  openapi.json
#   timestamp: 2025-05-02T05:12:50+00:00
#
# API Versioning Scheme
# ---------------------
# All API endpoints are served under the /api/v1/ prefix via a versioned router.
# Backward-compatible aliases are maintained at the original paths (e.g., /status/,
# /v1/task/) so that existing clients continue to work without changes.
# The /api/version endpoint returns the current API version and can be used by
# clients to discover supported versions.
#
# To introduce a v2 API in the future:
#   1. Create a new APIRouter with prefix="/api/v2"
#   2. Register new or modified endpoint handlers on that router
#   3. Include the v2 router on the app
#   4. Update the /api/version response to advertise the new version
#   5. Keep the v1 router active until clients have migrated

from __future__ import annotations

import importlib.metadata
import time
from typing import Annotated
from uuid import UUID

from argon2 import PasswordHasher, Type
from argon2.exceptions import VerifyMismatchError
from fastapi import APIRouter, Depends, FastAPI, HTTPException, Request, Response, status
from fastapi.security import HTTPBasic, HTTPBasicCredentials
from pydantic import BaseModel, Field
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.responses import PlainTextResponse
from urllib3.exceptions import MaxRetryError, NewConnectionError

from buttercup.common.logger import setup_package_logger
from buttercup.common.metrics import (
    HTTP_REQUEST_DURATION,
    HTTP_REQUESTS_TOTAL,
    QUEUE_DEPTH,
    REGISTRY,
)
from buttercup.common.queues import QueueNames, ReliableQueue
from buttercup.common.sarif_store import SARIFStore
from buttercup.orchestrator.api_client_factory import create_api_client
from buttercup.orchestrator.competition_api_client.api.ping_api import PingApi
from buttercup.orchestrator.competition_api_client.models.types_ping_response import TypesPingResponse
from buttercup.orchestrator.task_server.backend import (
    delete_all_tasks,
    delete_task,
    get_status_tasks_state,
    new_task,
    store_sarif_broadcast,
)
from buttercup.orchestrator.task_server.config import TaskServerSettings
from buttercup.orchestrator.task_server.dependencies import (
    get_delete_task_queue,
    get_redis,
    get_sarif_store,
    get_settings,
    get_task_queue,
)
from buttercup.orchestrator.task_server.models.types import SARIFBroadcast, Status, StatusState, Task
from buttercup.orchestrator.task_server.rate_limit import RateLimitMiddleware, RateLimitStore

# Paths that should be excluded from HTTP metrics recording (infrastructure endpoints).
_METRICS_SKIP_PATHS: set[str] = {"/metrics", "/healthz", "/readyz"}

# Current API version identifier. Bump this when releasing a new version of the API.
API_VERSION = "v1"

settings = get_settings()
logger = setup_package_logger("task-server", __name__, settings.log_level, settings.log_max_line_length)
logger.info("Redis URL: %s", settings.redis_url)
logger.info("Competition API URL: %s", settings.competition_api_url)
logger.info("Competition API Key ID: %s", settings.competition_api_username)
logger.info("API Key ID: %s", settings.api_key_id)

try:
    __version__ = importlib.metadata.version("orchestrator")
except importlib.metadata.PackageNotFoundError:
    __version__ = "0.0.0"

app = FastAPI(
    title="Buttercup CRS API",
    contact={},
    version=__version__,
    servers=[{"url": "/"}],
    log_config=None,
)

# ---------------------------------------------------------------------------
# HTTP metrics middleware
# ---------------------------------------------------------------------------


class MetricsMiddleware(BaseHTTPMiddleware):
    """Record request count and duration for every HTTP request."""

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        if request.url.path in _METRICS_SKIP_PATHS:
            return await call_next(request)

        start = time.monotonic()
        response = await call_next(request)
        elapsed = time.monotonic() - start

        method = request.method
        endpoint = request.url.path
        HTTP_REQUESTS_TOTAL.inc(method=method, endpoint=endpoint, status_code=str(response.status_code))
        HTTP_REQUEST_DURATION.observe(elapsed, method=method, endpoint=endpoint)
        return response


app.add_middleware(MetricsMiddleware)

# ---------------------------------------------------------------------------
# Rate limiting
# ---------------------------------------------------------------------------
rate_limit_store = RateLimitStore(
    general_limit=settings.rate_limit_general,
    heavy_limit=settings.rate_limit_heavy,
)
app.add_middleware(
    RateLimitMiddleware,
    store=rate_limit_store,
    enabled=settings.rate_limit_enabled,
)

# The exposed endpoints must be authenticated using HTTP Basic.
# Credentials will be composed of an API key and token which will be used as the username
# and password in HTTP Basic Auth.
# API keys will be UUIds, tokens will be random alphanumeric strings of at least 32 chars.
# Tokens are stored using Argon2ID.
security = HTTPBasic()

# Create password hasher with Argon2id
ph = PasswordHasher(
    time_cost=3,  # Number of iterations
    memory_cost=65536,  # 64MB
    parallelism=4,  # Number of parallel threads
    hash_len=32,  # Length of the hash in bytes
    salt_len=16,  # Length of the salt in bytes
    encoding="utf-8",  # Encoding of the password
    type=Type.ID,  # Argon2id
)

# Authentication settings are accessed through the settings object


class ApiToken(BaseModel):
    """Model representing an API token entry with its hashed value"""

    key_id: UUID = Field(..., description="UUID identifier for the API key")
    token_hash: str = Field(..., description="Argon2id hash of the token")


def check_auth(
    credentials: Annotated[HTTPBasicCredentials, Depends(security)],
    settings: Annotated[TaskServerSettings, Depends(get_settings)],
) -> str:
    """Authenticate user with Argon2id-hashed token.

    Args:
        credentials: HTTP Basic authentication credentials
        settings: Application settings containing authentication config

    Returns:
        The authenticated key_id on success

    Raises:
        HTTPException: If authentication fails

    """
    # Get expected key ID and token hash from settings
    expected_key_id = settings.api_key_id
    token_hash = settings.api_token_hash

    # If either setting is missing, authentication fails
    if not expected_key_id or not token_hash:
        logger.error(
            "Authentication configuration is missing. Configure BUTTERCUP_TASK_SERVER_API_KEY_ID and "
            "BUTTERCUP_TASK_SERVER_API_TOKEN_HASH environment variables.",
        )
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Authentication configuration error",
            headers={"WWW-Authenticate": "Basic"},
        )

    # Get credentials from request
    key_id = credentials.username
    token = credentials.password

    # Check if key ID matches
    if key_id != expected_key_id:
        logger.warning(f"Key ID from request ({key_id}) doesn't match expected key ID")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid API key",
            headers={"WWW-Authenticate": "Basic"},
        )

    # Verify token using Argon2id
    try:
        ph.verify(token_hash, token)
        return str(key_id)
    except VerifyMismatchError:
        logger.warning(f"Invalid token provided for key ID {key_id}")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid token",
            headers={"WWW-Authenticate": "Basic"},
        )


# ---------------------------------------------------------------------------
# Versioned API router: all v1 endpoints live under /api/v1/
# ---------------------------------------------------------------------------
v1_router = APIRouter(prefix="/api/v1", tags=["v1"])


@v1_router.get("/status/", response_model=Status, tags=["status"])
def get_status_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
) -> Status:
    """CRS Status"""

    def is_competition_api_ready() -> bool:
        is_ready = False
        api_client = create_api_client(
            competition_api_url=settings.competition_api_url,
            competition_api_username=settings.competition_api_username,
            competition_api_password=settings.competition_api_password,
        )
        api = PingApi(api_client=api_client)

        response: TypesPingResponse | None = None
        try:
            response = api.v1_ping_get()
        except (MaxRetryError, NewConnectionError):
            is_ready = False

        if isinstance(response, TypesPingResponse):
            if response.status:
                is_ready = True

        return is_ready

    return Status(
        details={},
        ready=is_competition_api_ready(),
        since=0,
        state=StatusState(tasks=get_status_tasks_state(settings.redis_url)),
        version=__version__,
    )


@v1_router.delete("/status/", response_model=str, tags=["status"])
def delete_status_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
) -> str:
    """Reset status stats"""
    logger.info("Resetting status")
    return ""


@v1_router.post("/sarif/", response_model=str, tags=["sarif"])
def post_v1_sarif_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
    body: SARIFBroadcast,
    sarif_store: Annotated[SARIFStore, Depends(get_sarif_store)],
) -> str:
    """Submit Sarif Broadcast"""
    logger.info("Accepting Sarif Broadcast: %s", body)
    return store_sarif_broadcast(body, sarif_store)


@v1_router.post(
    "/task/",
    response_model=None,
    responses={"202": {"model": str}},
    tags=["task"],
)
def post_v1_task_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
    body: Task,
    tasks_queue: Annotated[ReliableQueue, Depends(get_task_queue)],
) -> str | None:
    """Submit Task"""
    logger.debug("Accepting Task: %s", body)
    return new_task(body, tasks_queue)


@v1_router.delete("/task/", response_model=str, tags=["task"])
def delete_v1_task_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
    delete_task_queue: Annotated[ReliableQueue, Depends(get_delete_task_queue)],
) -> str:
    """Cancel All Tasks

    This endpoint allows canceling all existing tasks in the system. All tasks will be marked for deletion.

    Args:
        credentials: HTTP Basic authentication credentials required to access this endpoint
        delete_task_queue: Queue for processing task deletion requests

    Returns:
        str: Empty string on successful deletion request

    Raises:
        HTTPException: If authentication fails

    """
    logger.info("Deleting all tasks")
    return delete_all_tasks(delete_task_queue)


@v1_router.delete("/task/{task_id}/", response_model=str, tags=["task"])
def delete_v1_task_task_id_(
    credentials: Annotated[HTTPBasicCredentials, Depends(check_auth)],
    task_id: UUID,
    delete_task_queue: Annotated[ReliableQueue, Depends(get_delete_task_queue)],
) -> str:
    """Cancel a task by its ID.

    This endpoint allows canceling an existing task by its unique identifier. The task will be marked for deletion
    and removed from the system.

    Args:
        credentials: HTTP Basic authentication credentials required to access this endpoint
        task_id: The UUID of the task to cancel
        delete_task_queue: Queue for processing task deletion requests

    Returns:
        str: Empty string on successful deletion request

    Raises:
        HTTPException: If authentication fails

    """
    logger.info("Deleting task: %s", task_id)
    return delete_task(task_id, delete_task_queue)


# Register the versioned router on the app
app.include_router(v1_router)

# ---------------------------------------------------------------------------
# Backward-compatible aliases
# ---------------------------------------------------------------------------
# These routers re-mount the same endpoint handlers at the original (legacy)
# paths so that existing clients continue to work without modification.

legacy_root_router = APIRouter(tags=["legacy"])
legacy_root_router.add_api_route("/status/", get_status_, methods=["GET"], response_model=Status, tags=["status"])
legacy_root_router.add_api_route("/status/", delete_status_, methods=["DELETE"], response_model=str, tags=["status"])

legacy_v1_router = APIRouter(prefix="/v1", tags=["legacy"])
legacy_v1_router.add_api_route("/sarif/", post_v1_sarif_, methods=["POST"], response_model=str, tags=["sarif"])
legacy_v1_router.add_api_route(
    "/task/",
    post_v1_task_,
    methods=["POST"],
    response_model=None,
    responses={"202": {"model": str}},
    tags=["task"],
)
legacy_v1_router.add_api_route("/task/", delete_v1_task_, methods=["DELETE"], response_model=str, tags=["task"])
legacy_v1_router.add_api_route(
    "/task/{task_id}/", delete_v1_task_task_id_, methods=["DELETE"], response_model=str, tags=["task"]
)

app.include_router(legacy_root_router)
app.include_router(legacy_v1_router)


# ---------------------------------------------------------------------------
# Version discovery endpoint (unauthenticated)
# ---------------------------------------------------------------------------
@app.get("/healthz", tags=["health"])
def get_healthz() -> dict[str, str]:
    """Liveness probe. Always returns 200 to indicate the process is alive."""
    return {"status": "ok"}


@app.get("/readyz", tags=["health"])
def get_readyz() -> dict[str, str]:
    """Readiness probe. Returns 200 if Redis is reachable, 503 otherwise."""
    try:
        r = get_redis()
        r.ping()
    except Exception:  # Broad catch intentional: readiness probe must catch any Redis failure
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail="Redis is not available")
    return {"status": "ok"}


@app.get("/api/version", tags=["version"])
def get_api_version() -> dict[str, str]:
    """Return the current API version and application version.

    This endpoint is unauthenticated and can be used by clients to discover
    which API versions are supported by this server.
    """
    return {
        "api_version": API_VERSION,
        "app_version": __version__,
    }


# ---------------------------------------------------------------------------
# Prometheus-compatible metrics endpoint (unauthenticated)
# ---------------------------------------------------------------------------
@app.get("/metrics", tags=["metrics"], response_class=PlainTextResponse)
def get_metrics() -> PlainTextResponse:
    """Expose application metrics in Prometheus text exposition format.

    Queue depths are sampled on each request so that the gauge values
    reflect the current state of the Redis streams.
    """
    # Sample queue depths from Redis.
    try:
        r = get_redis()
        for qn in QueueNames:
            length = r.xlen(qn.value)
            QUEUE_DEPTH.set(float(length), queue_name=qn.value)
    except Exception:  # Broad catch intentional: metrics must not fail if Redis is down
        pass

    body = REGISTRY.collect()
    return PlainTextResponse(content=body, media_type="text/plain; version=0.0.4; charset=utf-8")
